name: Build Binaries
on: [push, pull_request]

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          install: git make unzip gcc libtool msys/autotools msys/autoconf-wrapper automake cmake msys/binutils mingw-w64-x86_64-libusb
      - name: Build libusb
        run: |
          git clone https://github.com/libusb/libusb.git
          cd ./libusb
          ./bootstrap.sh
          ./configure
          make -j$NUMBER_OF_PROCESSORS
          make install
      - name: Build libusb-compat-0.1
        run: |
          git clone https://github.com/libusb/libusb-compat-0.1.git
          cd ./libusb-compat-0.1
          ./bootstrap.sh
          ./configure
          make -j$NUMBER_OF_PROCESSORS
          make install
      - name: Build hidapi
        run: |
          git clone https://github.com/libusb/hidapi.git
          cd ./hidapi
          ./bootstrap
          ./configure
          make all -j$NUMBER_OF_PROCESSORS
          make install
      - name: Build AVaRICE
        run: |
          ./Bootstrap
          ./configure
          make -j$NUMBER_OF_PROCESSORS
          make install DESTDIR=$(pwd)/avarice_installed/
          ls -R avarice_installed
          file avarice_installed/usr/bin/*
          ldd avarice_installed/usr/bin/avarice
          cp /mingw64/bin/libusb-1.0.dll avarice_installed/usr/bin/.
          cp /usr/bin/msys-2.0.dll avarice_installed/usr/bin/.
          cp /usr/bin/msys-stdc++-6.dll avarice_installed/usr/bin/.
          cp /usr/bin/msys-gcc_s-seh-1.dll avarice_installed/usr/bin/.
          cp /usr/bin/msys-usb-0-1-4.dll avarice_installed/usr/bin/.
          cp /usr/bin/msys-hidapi-0.dll avarice_installed/usr/bin/.
      - name: Run AVaRICE
        run: |
          avarice_installed/usr/bin/avarice --version
          avarice_installed/usr/bin/avarice --known-devices || true
      - uses: actions/upload-artifact@v4
        with:
          name: AVaRICE Windows 64-bit
          path: avarice_installed
  build-lin64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make autotools-dev automake binutils-dev libusb-dev libhidapi-dev
      - name: Build AVaRICE
        run: |
          ./Bootstrap
          ./configure --enable-target-programming
          make -j$NUMBER_OF_PROCESSORS
          mkdir avarice_installed
          make install DESTDIR=$(pwd)/avarice_installed/
          file avarice_installed/usr/local/bin/*
          ldd avarice_installed/usr/local/bin/avarice
      - name: Run AVaRICE
        run: |
          avarice_installed/usr/local/bin/avarice --version
          avarice_installed/usr/local/bin/avarice --known-devices || true
      - name: Tar files
        run: tar -cvf avarice.tar.gz -C avarice_installed .
      - uses: actions/upload-artifact@v4
        with:
          name: AVaRICE Linux 64-bit
          path: avarice.tar.gz
  build-darwin-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: | 
          brew install gcc binutils autoconf automake mk-configure libusb libusb-compat hidapi
      - name: Build AVaRICE
        run: |
          ./Bootstrap
          # note: we use a constant hidapi include path instead of "pkg-config --cflags hidapi" because that path include  "/hidapi" at the end
          # through which in turn "hidapi/hidapi.h" will not be found (it would have to be just "hidapi.h").
          export CFLAGS="$(pkg-config --cflags libusb) $(pkg-config --cflags libusb-1.0) -I/opt/homebrew/Cellar/hidapi/0.14.0/include/"
          export CXXFLAGS="$(pkg-config --cflags libusb) $(pkg-config --cflags libusb-1.0) -I/opt/homebrew/Cellar/hidapi/0.14.0/include/"
          export LDFLAGS="$(pkg-config --libs-only-L libusb) $(pkg-config --libs-only-L libusb-1.0) $(pkg-config --libs-only-L hidapi)"
          ./configure
          make -j3
          mkdir avarice_installed
          make install DESTDIR=$(pwd)/avarice_installed/
          ls -R avarice_installed
          otool -L avarice_installed/usr/local/bin/avarice
          install_name_tool -change /opt/homebrew/opt/hidapi/lib/libhidapi.0.dylib @executable_path/./libhidapi.0.dylib ./avarice_installed/usr/local/bin/avarice
          install_name_tool -change /opt/homebrew/opt/libusb-compat/lib/libusb-0.1.4.dylib @executable_path/./libusb-0.1.4.dylib ./avarice_installed/usr/local/bin/avarice
          cp /opt/homebrew/opt/hidapi/lib/libhidapi.0.dylib ./avarice_installed/usr/local/bin/.
          cp /opt/homebrew/opt/libusb-compat/lib/libusb-0.1.4.dylib ./avarice_installed/usr/local/bin/.
          otool -L avarice_installed/usr/local/bin/avarice
      - name: Run AVaRICE
        run: |
          avarice_installed/usr/local/bin/avarice --version
          avarice_installed/usr/local/bin/avarice --known-devices || true
      - name: Tar files
        run: tar -cvf avarice.tar.gz -C avarice_installed .
      - uses: actions/upload-artifact@v4
        with:
          name: AVaRICE Mac OS ARM 64-bit
          path: avarice.tar.gz